latticejs/lattice

packages/dag/package.json
packages/dag/setupTest.js
packages/dag/test/enzyme.test.js
yarn.lock

Closes #43 
This PR adds _initial_ enzyme support.

Enzyme dag

---

lerna.json
packages/dag/package.json
packages/lattice/package.json
packages/mui-recharts/package.json
packages/react-scripts/package.json
packages/recharts-sunburst/package.json
packages/widgets/package.json

Prepare modules for lerna publish

---

packages/react-scripts/template/src/components/dashboard/Demographic.js
yarn.lock

Fix react script warning

---

.storybook/config.js
package.json
packages/dag/package.json
packages/dag/stories/index.js
packages/mui-recharts/.storybook/config.js
packages/mui-recharts/package.json
packages/mui-recharts/stories/index.js
packages/recharts-sunburst/.storybook/config.js
packages/recharts-sunburst/package.json
packages/recharts-sunburst/stories/index.js
packages/widgets/.storybook/config.js
packages/widgets/package.json
packages/widgets/stories/index.js
yarn.lock

added root storybook

---

packages/mui-recharts/README.md

mui-recharts: Readme

---

packages/dag/README.md

Add: dag readme (initial version)

---

packages/recharts-sunburst/README.md

Related to #53 
This PR adds an initial version of component's readme.

sunburst: readme 

---

packages/react-scripts/template/src/components/dashboard/AverageRevenue.js

Fix wrong scope for mui-recharts import

---

examples/README.md
lerna.json
package.json

Adding examples workspace. WIP.

examples workspace

---

packages/dag/src/index.js
packages/dag/test/enzyme.test.js
packages/mui-recharts/test/__snapshots__/storyshot.test.js.snap
packages/widgets/test/__snapshots__/storyshot.test.js.snap

This PR fixes #105 
Due to a limitation around [jsdom](https://github.com/jsdom/jsdom/issues/300)/enzyme a test was commented out. We may need to look for a proper solution and revisit this in the short term.

dag: fix mouse coords (svg <--> dom)

---

packages/dag/src/dag.js
packages/dag/src/edge.js
packages/dag/test/__snapshots__/storyshot.test.js.snap

dag: tweaks around config for static graph

---

packages/clap/lib/index.js
packages/clap/lib/messages.js
packages/clap/lib/tasks/index.js
packages/clap/lib/tasks/renamePkgName.js
packages/clap/test/lib.test.js

clap: add rename pkg name task

---

README.md

This PR is an initial version of what should solve #115.

Docs: add getting started info

---

packages/clap/package.json
yarn.lock

clap: add new bin (create-lattice-app) + add missing dep

---

README.md
packages/clap/README.md
packages/mui-recharts/test/__snapshots__/storyshot.test.js.snap

clap: fix clap usage (npx related)

---

examples/basic/src/App.js
examples/basic/src/Main.js
examples/basic/src/index.js

It closes #138 and it is also open to suggestions.
It currently adds theming support and some widgets usage displaying lattice features.

examples: improvements around basic example

---

packages/widgets/README.md
yarn.lock

This PR closes #144 by adding a brand new readme file.

widgets: add docs!

---

.storybook/addons.js
package.json
packages/infinite-list/.storybook/addons.js
packages/infinite-list/README.md
packages/infinite-list/__mocks__/storybook-readme.js
packages/infinite-list/package.json
packages/infinite-list/stories/list.js
packages/infinite-list/stories/table.js
packages/infinite-list/stories/utils.js
yarn.lock

WIP :cactus: 
* README.md
* storybook-readme support

infinite-list: add doc with storybook-readme support

---

examples/minimal/.babelrc
examples/minimal/.gitignore
examples/minimal/README.md
examples/minimal/package-lock.json
examples/minimal/package.json
examples/minimal/src/App.js
examples/minimal/src/Main.js
examples/minimal/src/index.html
examples/minimal/src/index.js
examples/minimal/webpack.config.js

This PR closes #163 
The main idea is to expose a simple lattice app using webpack and babel directly.

examples: new minimal example

---

package.json

chore(package): update lerna to version 3.1.2

---

packages/dag/src/index.js

DAG: move one lvl up the click handler on render panel actions

---

CONTRIBUTING.md

contributing: add "Creating Lattice packages" section

---

packages/dag/src/index.js

dag: add fill property to dag edge class

---

packages/dag/.storybook/webpack.config.js
packages/infinite-list/.storybook/webpack.config.js
packages/mui-recharts/.storybook/webpack.config.js
packages/recharts-sunburst/.storybook/webpack.config.js
packages/tree/.storybook/webpack.config.js
packages/widgets/.storybook/webpack.config.js

This PR fixes a bug with local storybooks webpack config.

Storybook: fix for local storybooks.

---

packages/dag/test/enzyme.test.js
packages/dag/test/shim.js
yarn.lock

This is a quick PR for adding back a missing test for edge creation.

dag: fix test for onEdgeAdded cb

---

packages/tree/README.md
packages/tree/src/tree.js
packages/tree/stories/tree.js
packages/tree/test/__snapshots__/storyshot.test.js.snap
packages/tree/test/tree.enzyme.test.js
yarn.lock

Tree: fix tree cascadeCheck

---

packages/dag/src/index.js
packages/dag/src/node.js
packages/dag/stories/index.js
packages/dag/test/__snapshots__/storyshot.test.js.snap

dag: fix for FF and safari coordinates after scroll/pan

---

examples/dag-in-action/src/App.js

dag: making use of node remove cb

---

package.json
packages/dag/test/__snapshots__/storyshot.test.js.snap
packages/infinite-list/test/__snapshots__/storyshot.test.js.snap
packages/mui-recharts/test/__snapshots__/storyshot.test.js.snap
packages/tree/test/__snapshots__/storyshot.test.js.snap
packages/widgets/test/__snapshots__/storyshot.test.js.snap
yarn.lock

Greenkeeper/eslint config prettier 3.1.0

---

package.json
packages/dag/package.json
packages/infinite-list/package.json
packages/mui-recharts/package.json
packages/recharts-sunburst/package.json
packages/storybook-readme/package.json
packages/tree/package.json
packages/tree/stories/pkg.json
yarn.lock

Greenkeeper/default/storybook readme 4.0.0

---

.storybook/webpack.config.js
package.json
packages/dag/.storybook/decorator-material-ui.js
packages/dag/package.json
packages/infinite-list/.storybook/decorator-material-ui.js
packages/infinite-list/package.json
packages/mui-recharts/.storybook/decorator-material-ui.js
packages/mui-recharts/package.json
packages/tree/.storybook/decorator-material-ui.js
packages/tree/package.json
packages/tree/test/__snapshots__/storyshot.test.js.snap
packages/widgets/.storybook/decorator-material-ui.js
packages/widgets/package.json
packages/widgets/src/Widget.js
packages/widgets/test/__snapshots__/storyshot.test.js.snap
packages/widgets/test/widget.enzyme.test.js
yarn.lock

Greenkeeper/default/monorepo.material ui 3.3.0

---

package.json
yarn.lock

Greenkeeper/prettier 1.14.3

---

.travis.yml
CHANGELOG.md
RELEASE.md
package.json
yarn.lock

Release from travis

---

examples/dag-in-action/src/App.js
packages/dag/src/index.js
packages/dag/src/node.js

Fix: eslint warnings

---

CHANGELOG.md
examples/apollo-enterprise/package.json
examples/apollo-real-time-chart/package.json
examples/dag-in-action/package.json

Update: normalize start script

---

CHANGELOG.md
examples/apollo-enterprise/src/components/dashboard/AverageRevenue.js
examples/apollo-enterprise/src/components/dashboard/Demographic.js
examples/apollo-enterprise/src/components/dashboard/NewCustomers.js
examples/apollo-enterprise/src/components/dashboard/Stats.js
examples/apollo-enterprise/src/components/dashboard/TaskScheduler.js
examples/apollo-enterprise/src/components/dashboard/TopProducts.js
examples/apollo-enterprise/src/components/employees/Form.js
examples/apollo-enterprise/src/containers/Main.js
examples/apollo-enterprise/src/containers/theme/General.js
examples/apollo-enterprise/src/containers/theme/Widgets.js
examples/apollo-real-time-chart/src/components/CPUUsage.js
examples/apollo-real-time-chart/src/components/DisksUsage.js
examples/apollo-real-time-chart/src/components/MemoryUsage.js
examples/apollo-real-time-chart/src/components/ProcessUsage.js
examples/basic/src/App.js

examples: use named imports

---

CONTRIBUTING.md

This PR adds a new entry to the troubleshooting section.

Update: add greenkeeper section for dealing with staled/errored PRs

---

packages/gauge/.babelrc
packages/gauge/.storybook/.babelrc
packages/gauge/.storybook/addons.js
packages/gauge/.storybook/config.js
packages/gauge/.storybook/decorator-material-ui.js
packages/gauge/.storybook/webpack.config.js
packages/gauge/README.md
packages/gauge/index.js
packages/gauge/package.json
packages/gauge/setupTest.js
packages/gauge/src/arc.js
packages/gauge/src/gauge.js
packages/gauge/src/index.js
packages/gauge/src/needle.js
packages/gauge/src/utils.js
packages/gauge/stories/gauge.js
packages/gauge/test/__snapshots__/storyshot.test.js.snap
packages/gauge/test/storyshot.test.js
yarn.lock

Update: gauge component initial attempt (wip)

---

CHANGELOG.md

Updated change log file

---

CHANGELOG.md
package.json
yarn.lock

In this PR Husky is updated form 2 to 3.0.7.

Husky is updated.

---

CHANGELOG.md
packages/infinite-list/package.json
packages/infinite-list/stories/list.js
packages/infinite-list/stories/table.js
packages/infinite-list/test/__snapshots__/storyshot.test.js.snap

In this PR, infinite list package has been updated with MUI version 4.5.2

Updated MUI version of inifinite-list package.

---

CHANGELOG.md
packages/mui-recharts/package.json

In this PR, MUI version has been updated to 4.5.2 in mui-recharts package.

Updated MUI version of mui-recharts package.

---

CHANGELOG.md
packages/tree/package.json
packages/tree/src/tree.js
packages/tree/test/__snapshots__/storyshot.test.js.snap
yarn.lock

Hi Rahul,
In This PR We have updated MUI version from 3.9.0 to 4.5.1.
Please review.
Thanks,
Suresh

Upgrade-MUI-Version-Package-Tree | Updated MUI version

---

CHANGELOG.md
packages/widgets/package.json
packages/widgets/src/SideMenu.js
packages/widgets/src/Widget.js
packages/widgets/stories/sidemenu.js
packages/widgets/stories/widget.js
packages/widgets/test/__snapshots__/storyshot.test.js.snap
packages/widgets/test/sidemenu.enzyme.test.js
packages/widgets/test/storyshot.test.js
yarn.lock

In this PR, MUI version has been updated in widgets package.

Updated MUI version in Widgets Package.

---

CHANGELOG.md
examples/dag-in-action/package.json
examples/dag-in-action/src/App.js
examples/dag-in-action/src/Main.js

In this PR, Dag-In-Action example has been upgraded with MUI version 4.6.1.

Upgrade Dag-In-Action example with Mui version 4.6.1.

---

CHANGELOG.md
examples/minimal-with-gulp/package.json
examples/minimal-with-gulp/src/App.js

In this PR, width of froala-editor has been added in minimal-with-gulp example.

Updating minimal with gulp example

---

CHANGELOG.md
package.json
packages/clap/package.json

In this PR CLAP is updated from beta.2 to beta.3.
Self Reviewed
Rahul Garg

CLAP Version update.

---

CHANGELOG.md
packages/ag-grid/README.md
packages/froala-editor/README.md
packages/map/README.md

In this PR, The Readme of the newly added Packages is updated.
Self Reviewed
Rahul Garg

Readme is updated.

---

CHANGELOG.md
packages/mui-recharts/package.json

In this PR, The MUI-Recharts package is now re-released with version 1.0.3. No major change but as this package required new publishing, so new version is now added.
Self Reviewed
Rahul Garg

Release MUI-Recharts

---

CHANGELOG.md
packages/clap/cli.js

In this PR, shebang line has been added on the top of the cli.js file.
Kindly Review,
Shivani Sharma

LJS-46 | Added shebang line in cli.js file

---

CHANGELOG.md
examples/basic/src/Main.js

In this PR, 'this' keyword has been removed in basic example of lattice as we are using props directly without 'this'.
Kindly Review,
Shivani Sharma

Fixed props issue in basic example

---

.gitignore
CHANGELOG.md
examples/saas-starter/.env

In this PR, .gitignore is changed as the env file for SAAS Starter is added.
Rahul Garg

LJS-117 | Git Ignore is changed as the env file for SAAS Starter is added.

---

CHANGELOG.md
packages/clap/lib/index.js

In this PR, the bug related to the clap default command is fixed.
Rahul Garg

LJS-130 | CLAP bug resolved.

---

CHANGELOG.md
packages/clap/package.json

In this PR, After testing the CLAP changes the package will now be published under a new version of 1.0.1-beta.12.
Rahul Garg

LJS-130 | Version is upgraded.

---

CHANGELOG.md
packages/widgets/README.md
packages/widgets/package.json
templates/cra-template-lattice-basic/README.md
templates/cra-template-lattice-basic/package.json
templates/cra-template-lattice-basic/template/src/Main.js
templates/cra-template-lattice-rechart-grid-map/README.md
templates/cra-template-lattice-rechart-grid-map/package.json

In this PR, Few licenses and readme are updated with the versions.
Rahul Garg

LJS-132 | Read me and Licenses are updated.
